# programa que leia um número inteiro e mostre sua tabuada.

print('==TABUADA==')
numero = int(input('Digite um número inteiro: '))

print('Número: {}'.format(numero))
print('{}x2={}'.format(numero, numero*2))
print('{}x3={}'.format(numero, numero*3))
print('{}x4={}'.format(numero, numero*4))
print('{}x5={}'.format(numero, numero*5))
print('{}x6={}'.format(numero, numero*6))
print('{}x7={}'.format(numero, numero*7))
print('{}x8={}'.format(numero, numero*8))
print('{}x9={}'.format(numero, numero*9))
print('{}x10={}'.format(numero, numero*10))
print('{}x11={}'.format(numero, numero*11))
print('{}x12={}'.format(numero, numero*12))
print('{}x13={}'.format(numero, numero*13))
print('{}x14={}'.format(numero, numero*14))
print('{}x15={}'.format(numero, numero*15))
print('{}x16={}'.format(numero, numero*16))
print('{}x17={}'.format(numero, numero*17))
print('{}x18={}'.format(numero, numero*18))
print('{}x19={}'.format(numero, numero*19))
print('{}x20={}'.format(numero, numero*20))

# deu certo 🥳 (versão antes de assistir a aula do exercício)
